export function formatExpert(profile) {
  const user = profile.user
  const photo = profile.profilePhoto || user?.avatar || ''
  const profileVisibility = {
    bio: profile.profileVisibility?.bio !== false,
    experience: profile.profileVisibility?.experience !== false,
    skills: profile.profileVisibility?.skills !== false,
    education: profile.profileVisibility?.education !== false,
    certificates: profile.profileVisibility?.certificates !== false,
    achievements: profile.profileVisibility?.achievements !== false,
    reviews: profile.profileVisibility?.reviews !== false,
  }
  return {
    _id: profile._id,
    userId: user?._id,
    name: user?.name,
    profilePhoto: photo,
    avatar: photo,
    bio: profileVisibility.bio ? profile.bio : '',
    experience: profileVisibility.experience ? profile.experience : '',
    languages: profileVisibility.skills ? profile.languages || [] : [],
    skills: profileVisibility.skills ? profile.skills || [] : [],
    education: profileVisibility.education ? profile.education || [] : [],
    certificates: profileVisibility.certificates ? profile.certificates || [] : [],
    achievements: profileVisibility.achievements ? profile.achievements || [] : [],
    profileVisibility,
    hourlyPrice: profile.hourlyPrice,
    questionPrice: profile.questionPrice,
    pricePerQuestion: profile.questionPrice,
    completedAnswers: profile.completedAnswers,
    averageRating: profileVisibility.reviews ? profile.averageRating : 0,
    totalRatings: profileVisibility.reviews ? profile.totalRatings : 0,
    reviewCount: profileVisibility.reviews ? profile.totalRatings : 0,
    responseTime: profile.responseTime,
    responseTimeHours: profile.responseTime,
    availability: profile.availability,
    isAvailable: profile.availability === 'available',
    videoCallAvailable: profile.videoCallAvailable ?? false,
    isVerified: profile.isVerified,
    status: profile.status,
    category: profile.category,
    expertType: profile.expertType,
    categories: profile.categories || [],
    expertTypes: profile.expertTypes || [],
    activeAssignments: profile.activeAssignments,
    maxAssignments: profile.maxAssignments,
  }
}
